name: Docker Image Scan with VirusTotal

on:
  push:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - 'examples/**/package.json'
      - 'examples/**/poetry.lock'
      - 'examples/**/pyproject.toml'
      - 'examples/**/requirements.txt'
      - 'macapp/package.json'

  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - 'examples/**/package.json'
      - 'examples/**/poetry.lock'
      - 'examples/**/pyproject.toml'
      - 'examples/**/requirements.txt'
      - 'macapp/package.json'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t test-ollama:test --build-arg CUDA_V11_ARCHITECTURES="86" --build-arg CUDA_V12_ARCHITECTURES="90a" .

    - name: Save Docker image to tarball
      run: |
        python3 -m pip install tarsplit
        docker save test-ollama:test | gzip > image.tar.gz
        # seemed like when 4 parts were requested, 3 were generated
        tarsplit image.tar.gz 5
        # get the size of each part
        ls -lah | grep part
    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v4
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          ./image.tar.gz-part-1-of-5
          ./image.tar.gz-part-2-of-5
          ./image.tar.gz-part-3-of-5
          ./image.tar.gz-part-4-of-5
