name: Docker Image Scan with VirusTotal

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t test-ollama:test --build-arg CUDA_V11_ARCHITECTURES="86" --build-arg CUDA_V12_ARCHITECTURES="90a".

    - name: Save Docker image to tarball
      run: |
        docker save test-ollama:test | gzip > image.tar.gz

    - name: Upload Docker image to VirusTotal
      run: |
        curl -s --request POST "https://www.virustotal.com/api/v3/files" \
          --header "x-apikey: ${{ secrets.VT_API_KEY }}" \
          --form "file=@image.tar.gz" | jq '.data.id' > result.json

    - name: Get VirusTotal scan report
      run: |
        FILE_ID=$(jq -r '.data.id' result.json)
        echo "File ID: $FILE_ID"

        curl -s --request GET "https://www.virustotal.com/api/v3/files/$FILE_ID" \
          --header "x-apikey: ${{ secrets.VT_API_KEY }}" | jq '.data.attributes.last_analysis_stats'
